
CREATE TABLE CLIENTE 
( 
  CLIENTE_ID        NUMBER PRIMARY KEY,
  NOMBRE           VARCHAR2(500 BYTE), 
  CLAVE            VARCHAR2(10 BYTE), 
  MAIL             VARCHAR2(1000 BYTE), 
  ESTATUS          VARCHAR2(1000 BYTE) 
); 
 
BEGIN 
    FOR CLIENTE IN 1..10 
    LOOP 
       Insert into CLIENTE (CLIENTE_ID, NOMBRE, CLAVE, MAIL, ESTATUS) Values 
(CLIENTE, 'CLIENTE ' || CLIENTE, 'CLIE_' || CLIENTE, 'cliente'||CLIENTE||'@clie.com', 'ACTIVO'); 
    END LOOP; 
        UPDATE CLIENTE SET ESTATUS = 'INACTIVO' WHERE CLIENTE_ID IN (3,7,10); 
    COMMIT; 
END; 

CREATE TABLE PRODUCTO 
( 
  PRODUCTO_ID     NUMBER PRIMARY KEY, 
  DESCRIPCION     VARCHAR2(500 BYTE), 
  COSTO_UNITARIO  NUMBER, 
  ESTATUS          VARCHAR2(1000 BYTE) 
); 
 
BEGIN 
    FOR PRODUCTO IN 1..15 
    LOOP 
       Insert into PRODUCTO(PRODUCTO_ID, DESCRIPCION, COSTO_UNITARIO, 
ESTATUS) Values (PRODUCTO, 'PRODUCTO ' || PRODUCTO, ROUND(dbms_random.value(1, 
9999),2), 'ACTIVO'); 
    END LOOP; 
        UPDATE PRODUCTO SET ESTATUS = 'INACTIVO' WHERE PRODUCTO_ID IN (5,11,13); 
    COMMIT; 
END; 
 

CREATE TABLE VENTA 
( 
VENTA_ID     NUMBER PRIMARY KEY, 
FECHA        DATE, 
CLIENTE_ID   NUMBER, 
ESTATUS      VARCHAR2(100 byte),
CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_ID) 
    REFERENCES CLIENTE (CLIENTE_ID)
); 

CREATE TABLE DETALLE_VENTA 
( 
VENTA_ID     NUMBER, 
PRODUCTO_ID  NUMBER, 
CANTIDAD     NUMBER, 
DESCUENTO    NUMBER, 
TOTAL        NUMBER,
CONSTRAINT FK_VENTA FOREIGN KEY (VENTA_ID) 
    REFERENCES VENTA (VENTA_ID)
);